# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mmoliele <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/05/24 18:31:59 by mmoliele          #+#    #+#              #
#    Updated: 2017/05/24 18:41:19 by mmoliele         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = replace
FLAG = -Wall -Wextra -Werror -o
SRC = losers.cpp Sed4Losers.cpp

all:
	@clang++ $(FLAG) $(NAME) $(SRC)

clean:
	@/bin/rm -f $(NAME)
